import type { TailwindClassCategories } from "@/types/tailwind";
import { combineDefaultStyles } from "@/utils/tailwindHelper";
import { cva } from "class-variance-authority";

export const textStyles = cva(
  combineDefaultStyles({
    default: {
      responsive: "",
      layout: "",
      sizing: "",
      spacing: "",
      visual: "",
      typography: "text-gray-900",
      interactive: "",
      behavior: "",
    } satisfies TailwindClassCategories,
  }),
  {
    variants: {
      variant: {
        h1: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-4xl font-bold",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        h2: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-3xl font-semibold",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        h3: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-2xl font-semibold",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        h4: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-xl font-medium",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        body: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-base",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        caption: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-sm text-gray-600",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        small: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-xs text-gray-500",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
      },
      color: {
        primary: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-primary-600",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        secondary: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-gray-600",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        success: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-green-600",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        warning: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-yellow-600",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        error: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "",
          typography: "text-red-600",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
      },
    },
    defaultVariants: {
      variant: "body",
      color: "primary",
    },
  }
);
