import type { TailwindClassCategories } from "@/types/tailwind";
import { combineDefaultStyles } from "@/utils/tailwindHelper";
import { cva } from "class-variance-authority";

export const iconStyles = cva(
  combineDefaultStyles({
    default: {
      responsive: "",
      layout: "inline-flex",
      sizing: "w-5 h-5",
      spacing: "",
      visual: "",
      typography: "",
      interactive: "",
      behavior: "",
    } satisfies TailwindClassCategories,
  }),
  {
    variants: {
      size: {
        xs: {
          responsive: "",
          layout: "",
          sizing: "w-3 h-3",
          spacing: "",
          visual: "",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        sm: {
          responsive: "",
          layout: "",
          sizing: "w-4 h-4",
          spacing: "",
          visual: "",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        md: {
          responsive: "",
          layout: "",
          sizing: "w-5 h-5",
          spacing: "",
          visual: "",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        lg: {
          responsive: "",
          layout: "",
          sizing: "w-6 h-6",
          spacing: "",
          visual: "",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        xl: {
          responsive: "",
          layout: "",
          sizing: "w-8 h-8",
          spacing: "",
          visual: "",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
      },
      color: {
        current: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-current",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        primary: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-primary-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        secondary: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-gray-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        success: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-green-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        warning: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-yellow-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        error: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-red-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
      },
    },
    defaultVariants: {
      size: "md",
      color: "current",
    },
  }
);
