import type { TailwindClassCategories } from "@/types/tailwind";
import { combineDefaultStyles } from "@/utils/tailwindHelper";
import { cva } from "class-variance-authority";

export const spinnerStyles = cva(
  combineDefaultStyles({
    default: {
      responsive: "",
      layout: "inline-block",
      sizing: "",
      spacing: "",
      visual:
        "border-2 border-solid border-current border-r-transparent rounded-full",
      typography: "",
      interactive: "",
      behavior: "animate-spin",
    } satisfies TailwindClassCategories,
  }),
  {
    variants: {
      size: {
        xs: {
          responsive: "",
          layout: "",
          sizing: "h-3 w-3",
          spacing: "",
          visual: "border",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        sm: {
          responsive: "",
          layout: "",
          sizing: "h-4 w-4",
          spacing: "",
          visual: "border",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        md: {
          responsive: "",
          layout: "",
          sizing: "h-6 w-6",
          spacing: "",
          visual: "border-2",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        lg: {
          responsive: "",
          layout: "",
          sizing: "h-8 w-8",
          spacing: "",
          visual: "border-2",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        xl: {
          responsive: "",
          layout: "",
          sizing: "h-12 w-12",
          spacing: "",
          visual: "border-4",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
      },
      color: {
        primary: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-blue-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        secondary: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-gray-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        success: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-green-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        warning: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-yellow-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        error: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-red-600",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
        white: {
          responsive: "",
          layout: "",
          sizing: "",
          spacing: "",
          visual: "text-white",
          typography: "",
          interactive: "",
          behavior: "",
        } satisfies TailwindClassCategories,
      },
    },
    defaultVariants: {
      size: "md",
      color: "primary",
    },
  }
);
